/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our Samples at https://docs.gradle.org/8.10/samples
 */

plugins {
    id("jvm.conventions")
    id("playground")
    alias(libs.plugins.detekt)
}

val projectGroup = extra["echo.group"]!! // Arroja una excepción si no se encuentra la propiedad
val projectVersion = libs.versions.echo.get()

allprojects {
    group = projectGroup
    version = projectVersion
}
